add test_memory_size

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -16,9 +16,16 @@ if [ $? -ne 0 ]; then
 fi
 
 # ensure package and project versions match
-pytest -k test_version --quiet
+pytest -k test_version
 if [ $? -ne 0 ]; then
     echo "version mismatch. Aborting commit."
+    exit 1
+fi
+
+# ensure memory size tests pass
+pytest -k test_memory_size
+if [ $? -ne 0 ]; then
+    echo "memory size test errors. Aborting commit."
     exit 1
 fi
 
